In [1]:
# 1. Read Dataset
# 2. Extract valuable features
# 3. Data preprocessing
#   3.1 Remove strings from data
#   3.2 Informations are equal to each other
# 4. Divide dataset to train and test set
# 5. Create Neural Network
# 6. Compile and Fit
# 7. Let's predict
# 8. Congrats!

In [2]:
import pandas as pd
from torch.utils import tensorboard

In [3]:
dataframe = pd.read_csv("Churn_Modelling.csv")
dataframe.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
dataframe = dataframe.iloc[:, 3:]
dataframe.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [5]:
x = dataframe.iloc[:, :-1].values
y = dataframe.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import LabelEncoder
gender_encoder = LabelEncoder()
country_encoder = LabelEncoder()
x[:, 2] = gender_encoder.fit_transform(x[:, 2])
x[:, 1] = country_encoder.fit_transform(x[:, 1])
x[:, 1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-0.32622142, -0.90188624, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [8]:
import torch
from torch import nn
from torch.nn import functional as F

class ArtificialNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_layer = nn.Linear(10, 32)
        self.hidden_layer1 = nn.Linear(32, 64)
        self.hidden_layer2 = nn.Linear(64, 128)
        self.hidden_layer3 = nn.Linear(128, 32)
        self.output_layer = nn.Linear(32, 1)
        self.dropout = nn.Dropout(0.2)
        
    def forward(self, x):
        x = self.input_layer(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.hidden_layer1(x)
        x = F.relu(x)
        x = self.dropout(x)
        x = self.hidden_layer2(x)
        x = F.relu(x)
        x = self.hidden_layer3(x)
        x = F.relu(x)
        x = self.output_layer(x)
        y = F.sigmoid(x)
        
        return y
    

In [9]:
x = torch.from_numpy(x)
y = torch.from_numpy(y).view(-1, 1)
tensord_dataset = torch.utils.data.TensorDataset(x, y)

In [10]:
train_set, test_set = torch.utils.data.random_split(tensord_dataset, [int(0.8*x.shape[0]), int(0.2*x.shape[0])])
train_loader = torch.utils.data.DataLoader(train_set, batch_size=32, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=32, shuffle=True)

In [11]:
model = ArtificialNeuralNetwork()
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

nb_epoch = 50
summary = tensorboard.SummaryWriter()
for n in range(nb_epoch):
    for i, data in enumerate(train_loader):
        input_data, label = data
        input_data = torch.autograd.Variable(input_data).float()
        label = torch.autograd.Variable(label).float()
        y_pred = model(input_data)
        loss = criterion(label, y_pred)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        accuracy = (torch.round(y_pred.data) == label).sum()/float(len(label)) 
        summary.add_scalar("loss/train", loss.item(), i + n*len(train_loader))
        summary.add_scalar("acc/train", accuracy, i + n*len(train_loader))
    
    test_loss = 0
    test_acc = 0
    with torch.no_grad():
        for i, data in enumerate(test_loader):
                input_data, label = data
                input_data = torch.autograd.Variable(input_data).float()
                label = torch.autograd.Variable(label).float()
                y_pred = model(input_data)
                loss = criterion(y_pred, label)
                test_loss += loss.item()
                test_acc += (torch.round(y_pred.data) == label).sum()/float(len(label)) 
        test_loss /= len(test_loader)
        test_acc /= len(test_loader)
        summary.add_scalar("loss/test", test_loss, n)
        summary.add_scalar("acc/test", test_acc, n)
    print(f"Epoch: {n} Training loss: {loss.item()} acc: {accuracy} Test loss: {test_loss} acc: {test_acc}")
    summary.flush()

C:\anaconda3\envs\pytorch-python37\lib\site-packages\torch\nn\functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


Epoch: 0 Training loss: 0.15672507882118225 acc: 0.8125 Test loss: 0.14120766171623791 acc: 0.7961309552192688
Epoch: 1 Training loss: 0.15870654582977295 acc: 0.8125 Test loss: 0.12839352067500825 acc: 0.8328372836112976
Epoch: 2 Training loss: 0.0806858092546463 acc: 0.90625 Test loss: 0.11997147531263412 acc: 0.841269850730896
Epoch: 3 Training loss: 0.07812631875276566 acc: 0.84375 Test loss: 0.11378643620345327 acc: 0.8541666865348816
Epoch: 4 Training loss: 0.03921988978981972 acc: 0.84375 Test loss: 0.11863517637054126 acc: 0.8457341194152832
Epoch: 5 Training loss: 0.13743212819099426 acc: 0.8125 Test loss: 0.11322422875534921 acc: 0.8492063283920288
Epoch: 6 Training loss: 0.13038530945777893 acc: 0.9375 Test loss: 0.10954906974756529 acc: 0.8546627163887024
Epoch: 7 Training loss: 0.13970574736595154 acc: 0.84375 Test loss: 0.11360507452535251 acc: 0.8506944179534912
Epoch: 8 Training loss: 0.2533775568008423 acc: 0.78125 Test loss: 0.1103798272235999 acc: 0.85317462682724
Ep

In [12]:
model.eval()
correct = 0
batch_size=32
with torch.no_grad():
    for i, data in enumerate(test_loader):
            input_data, label = data
            input_data = torch.autograd.Variable(input_data).float()
            label = torch.autograd.Variable(label).float()
            y_pred = model(input_data)
            loss = criterion(y_pred, label)
            y_pred = torch.round(y_pred.data)
            correct += (y_pred == label).sum() 
    accuracy = correct/float(len(test_loader)*batch_size)
    print(f"Accuracy = {accuracy.item()}")

Accuracy = 0.8566468358039856


In [17]:
print(y_pred)
print(label)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.]])


In [61]:
print(len(test_loader))

63
